import = [
	"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
	]

[font]
size = 12.0

[font.bold]
family = "hack"
style = "Bold"

[font.bold_italic]
family = "hack"
style = "Bold Italic"

[font.italic]
family = "hack"
style = "Italic"

[font.normal]
family = "hack"
style = "Regular"

